name = "demi21.1"
author = "Grey Cat"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fba3fd8295b6d09ffac35c8a025297273f32558024428e00bff016879feb5ca"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = []
