name = "demi21.1"
author = "Grey Cat"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39c23f0c48af8ea5fba8e46751e2ec858c6386461ea3c9515e2196db8ac9087c"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = []
